FROM node:16-alpine
WORKDIR /client
COPY package*.json ./

RUN npm install --force
COPY . .
RUN npm run build

FROM nginx:1.23-alpine as production
COPY --from=build /client/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx","-g","daemon off;"]