FROM node:16-alpine as builder
WORKDIR /client
COPY package*.json ./

RUN npm install --force
COPY . .
RUN npm run build

FROM nginx:1.23-alpine as production
COPY --from=builder /client/build ./usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY ./nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx","-g","daemon off;"]